#!/bin/bash

echo "=========================================="
echo "GitHub Repository Setup for TYC"
echo "=========================================="
echo ""
echo "Step 1: Create the repository on GitHub"
echo "----------------------------------------"
echo "1. Go to: https://github.com/new"
echo "2. Repository name: TYC"
echo "3. Description: Tamale Youth Choir Website - React + FastAPI"
echo "4. Choose: Public or Private"
echo "5. DO NOT initialize with README, .gitignore, or license"
echo "6. Click 'Create repository'"
echo ""
echo "Step 2: Push your code"
echo "----------------------------------------"
echo "After creating the repository, run this command:"
echo ""
echo "git push -u origin main"
echo ""
echo "Note: GitHub requires a Personal Access Token (not password)"
echo "If prompted for password, use your Personal Access Token"
echo ""
echo "To create a Personal Access Token:"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token' -> 'Generate new token (classic)'"
echo "3. Give it a name: 'TYC-Website'"
echo "4. Select scope: 'repo' (full control of private repositories)"
echo "5. Click 'Generate token'"
echo "6. Copy the token and use it as your password when pushing"
echo ""
echo "=========================================="

